### ISSUE TITLE
Incorporating JAX

### ISSUE THREAD

**Issue by signorgelato** [differential-machine-learning/notebooks#1]
Is there any plan to leverage tools like [JAX](https://github.com/google/jax) (autograd+XLA)?

**Comment by differential-machine-learning** [comment]
No plan but happy to discuss and consider possibilities. The notebooks in this repo are designed for demonstration purposes, to clarify the concepts of the paper, demonstrate a practical implementation and show results. The industrial-strength code developed in Danske Bank's proprietary systems is very different.

**Comment by signorgelato** [comment]
I was mainly thinking of the possibility of writing native Python and Numpy code at least in the prototyping stage and then leverage JAX to speed things up on accelerators.
